# Run build-ns3
name: build-ns3

on: 
  push:
    paths:
      - '**.cc'
      - '**.h'
      - '**/wscript'
      - 'pre.sh'
      - 'post.sh'
  pull_request:
    paths:
      - '**.cc'
      - '**.h'
      - '**/wscript'
      - 'pre.sh'
      - 'post.sh'

jobs:
  build-on-ns3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ns3 build
      uses: marshallasch/ns3-action@32.3
      with:
        location: 'contrib'
        pre_run: 'pre.sh'
        post_run: 'post.sh'
        sim_name: 'rhpman-example'
        sim_args: '--runTime=120'
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: /output/results.txt
